# Generated by Django 5.2.4 on 2026-02-10 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compartimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('x1', models.PositiveIntegerField()),
                ('y1', models.PositiveIntegerField()),
                ('x2', models.PositiveIntegerField()),
                ('y2', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('imagen', models.ImageField(upload_to='vehiculos/')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_esperada', models.PositiveIntegerField(default=1)),
                ('compartimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.compartimento')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ok', 'Completo'), ('faltante', 'Faltante'), ('danado', 'Dañado')], default='ok', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.item')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_revision', to='inventario.revision')),
            ],
        ),
        migrations.AddField(
            model_name='revision',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='inventario.vehiculo'),
        ),
        migrations.AddField(
            model_name='compartimento',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartimentos', to='inventario.vehiculo'),
        ),
    ]
