# Generated by Django 5.2.4 on 2026-02-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compartimento',
            name='x1',
        ),
        migrations.RemoveField(
            model_name='compartimento',
            name='x2',
        ),
        migrations.RemoveField(
            model_name='compartimento',
            name='y1',
        ),
        migrations.RemoveField(
            model_name='compartimento',
            name='y2',
        ),
    ]
