# Generated by Django 5.2.4 on 2026-02-16 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_compartimento_x1_remove_compartimento_x2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrevision',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemrevision',
            name='revision',
        ),
        migrations.AlterModelOptions(
            name='compartimento',
            options={'ordering': ['vehiculo', 'orden', 'nombre'], 'verbose_name': 'Compartimento', 'verbose_name_plural': 'Compartimentos'},
        ),
        migrations.AlterModelOptions(
            name='revision',
            options={'ordering': ['-fecha'], 'verbose_name': 'Revisión', 'verbose_name_plural': 'Revisiones'},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['codigo'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AddField(
            model_name='compartimento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compartimento',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de visualización'),
        ),
        migrations.AddField(
            model_name='revision',
            name='observaciones_generales',
            field=models.TextField(blank=True, help_text='Observaciones generales de la revisión'),
        ),
        migrations.AddField(
            model_name='revision',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la revisión', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el vehículo está activo en el inventario'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='compartimento',
            name='nombre',
            field=models.CharField(help_text='Nombre del compartimento (ej: Lateral izquierdo)', max_length=100),
        ),
        migrations.AlterField(
            model_name='compartimento',
            name='vehiculo',
            field=models.ForeignKey(help_text='Vehículo al que pertenece este compartimento', on_delete=django.db.models.deletion.CASCADE, related_name='compartimentos', to='inventario.vehiculo'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la revisión'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='responsable',
            field=models.CharField(help_text='Nombre o grupo responsable de la revisión', max_length=100),
        ),
        migrations.AlterField(
            model_name='revision',
            name='vehiculo',
            field=models.ForeignKey(help_text='Vehículo que se está revisando', on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='inventario.vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='codigo',
            field=models.CharField(help_text='Código único del vehículo (ej: PMH-01)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Foto del vehículo', null=True, upload_to='vehiculos/'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre descriptivo del vehículo', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='compartimento',
            unique_together={('vehiculo', 'nombre')},
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del equipo (ej: Manguera 50mm)', max_length=200)),
                ('cantidad_esperada', models.PositiveIntegerField(default=1, help_text='Cantidad esperada de este equipo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('activo', models.BooleanField(default=True)),
                ('compartimento', models.ForeignKey(help_text='Compartimento al que pertenece este equipo', on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='inventario.compartimento')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['compartimento', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('si', 'SI'), ('no', 'NO'), ('pendiente', 'Pendiente')], default='pendiente', help_text='Estado del equipo: SI, NO, o Pendiente', max_length=10)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones específicas sobre este equipo')),
                ('revision', models.ForeignKey(help_text='Revisión a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_revision', to='inventario.revision')),
                ('equipo', models.ForeignKey(help_text='Equipo que se está revisando', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_revision', to='inventario.equipo')),
            ],
            options={
                'verbose_name': 'Detalle de Revisión',
                'verbose_name_plural': 'Detalles de Revisión',
                'unique_together': {('revision', 'equipo')},
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemRevision',
        ),
    ]
